/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    CommonDatePicker: typeof import('./../components/common/common-date-picker.vue')['default']
    CommonDialog: typeof import('./../components/common/common-dialog.vue')['default']
    CommonField: typeof import('./../components/common/common-field.vue')['default']
    CommonLabel: typeof import('./../components/common/common-label.vue')['default']
    HeaderDashboard: typeof import('./../components/layout/dashboard/header-dashboard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarDashboard: typeof import('./../components/layout/dashboard/sidebar-dashboard.vue')['default']
  }
}
