/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    CommonDialog: typeof import('./../components/common/common-dialog.vue')['default']
    CommonField: typeof import('./../components/common/common-field.vue')['default']
    CommonLabel: typeof import('./../components/common/common-label.vue')['default']
    HeaderDashboard: typeof import('./../components/layout/dashboard/header-dashboard.vue')['default']
    LayoutPartialPage: typeof import('./../components/layout/partials/layout-partial-page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarDashboard: typeof import('./../components/layout/dashboard/sidebar-dashboard.vue')['default']
  }
}
